PRODUCT_VERSION_MAJOR = 15
PRODUCT_VERSION_MINOR = 0

# Increase TenX Version with each major release.
TENX_VERSION := 2.0

ifeq ($(WITH_MINI_GMS), true)
    TENX_EDITION ?= CORE 
else
    TENX_EDITION ?= PIXEL
endif

# Internal version
LINEAGE_VERSION := TenX-OS-v$(TENX_VERSION)-$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(shell date +%Y%m%d)-$(LINEAGE_BUILD)-$(TENX_EDITION)

# Display version
LINEAGE_DISPLAY_VERSION := TenX-OS-$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(LINEAGE_BUILD)-v$(TENX_VERSION)-$(TENX_EDITION)
